import type { Conversation, Message, LogEvent, DashboardStats } from './types'

const now = Date.now()
const mins = (m: number) => new Date(now - m * 60000).toISOString()
const hrs = (h: number) => new Date(now - h * 3600000).toISOString()

export const mockConversations: Conversation[] = [
  {
    id: '1',
    whatsapp_phone: '+5491112345678',
    whatsapp_profile_name: 'Juan Pérez',
    customer_name: 'Juan Pérez',
    source: 'whatsapp',
    status: 'ia_activa',
    ai_enabled: true,
    funnel_stage: 'calificando_viaje',
    ai_summary: 'Cliente interesado en Cancún para 2 personas en julio.',
    next_action: 'Enviar opciones de hoteles',
    next_follow_up_at: null,
    assigned_to: null,
    priority: 'high',
    unread_count: 2,
    last_message_preview: 'Entre 25,000 y 30,000 pesos por persona.',
    last_message_at: mins(5),
    last_inbound_at: mins(5),
    last_outbound_at: mins(4),
    internal_notes: null,
    created_at: mins(30),
    updated_at: mins(4),
  },
  {
    id: '2',
    whatsapp_phone: '+5491198765432',
    whatsapp_profile_name: 'María Gómez',
    customer_name: 'María Gómez',
    source: 'whatsapp',
    status: 'esperando_humano',
    ai_enabled: false,
    funnel_stage: 'interesado',
    ai_summary: null,
    next_action: null,
    next_follow_up_at: null,
    assigned_to: null,
    priority: 'high',
    unread_count: 1,
    last_message_preview: '¿Tienen disponibilidad para viajar en julio?',
    last_message_at: mins(15),
    last_inbound_at: mins(15),
    last_outbound_at: null,
    internal_notes: null,
    created_at: hrs(1),
    updated_at: mins(15),
  },
  {
    id: '3',
    whatsapp_phone: '+5491187654321',
    whatsapp_profile_name: 'Carlos López',
    customer_name: 'Carlos López',
    source: 'whatsapp',
    status: 'humano_activo',
    ai_enabled: false,
    funnel_stage: 'presupuesto_en_armado',
    ai_summary: null,
    next_action: null,
    next_follow_up_at: null,
    assigned_to: 'Admin',
    priority: 'normal',
    unread_count: 0,
    last_message_preview: 'Hola Carlos, te habla el equipo de Hermes...',
    last_message_at: mins(20),
    last_inbound_at: mins(25),
    last_outbound_at: mins(20),
    internal_notes: 'Cliente interesado en Europa 15 días. Presupuesto alto.',
    created_at: hrs(2),
    updated_at: mins(20),
  },
  {
    id: '4',
    whatsapp_phone: '+5491176543210',
    whatsapp_profile_name: 'Laura Álvarez',
    customer_name: 'Laura Álvarez',
    source: 'whatsapp',
    status: 'ia_activa',
    ai_enabled: true,
    funnel_stage: 'calificando_viaje',
    ai_summary: null,
    next_action: null,
    next_follow_up_at: null,
    assigned_to: null,
    priority: 'normal',
    unread_count: 0,
    last_message_preview: 'Gracias, me pueden enviar más opciones de hoteles.',
    last_message_at: mins(45),
    last_inbound_at: mins(45),
    last_outbound_at: mins(40),
    internal_notes: null,
    created_at: hrs(3),
    updated_at: mins(40),
  },
  {
    id: '5',
    whatsapp_phone: '+5491165432109',
    whatsapp_profile_name: 'Roberto Fernández',
    customer_name: 'Roberto Fernández',
    source: 'whatsapp',
    status: 'cerrada',
    ai_enabled: false,
    funnel_stage: 'perdido',
    ai_summary: null,
    next_action: null,
    next_follow_up_at: null,
    assigned_to: null,
    priority: 'low',
    unread_count: 0,
    last_message_preview: '¿Incluye vuelos y hospedaje?',
    last_message_at: hrs(2),
    last_inbound_at: hrs(2),
    last_outbound_at: hrs(1),
    internal_notes: null,
    created_at: hrs(5),
    updated_at: hrs(1),
  },
]

export const mockMessages: Record<string, Message[]> = {
  '1': [
    { id: 'm1', conversation_id: '1', whatsapp_message_id: 'wamid.1', direction: 'inbound', sender_type: 'customer', message_type: 'text', text: 'Hola, quiero información sobre sus paquetes a Cancún.', status: 'received', error_detail: null, created_at: mins(30) },
    { id: 'm2', conversation_id: '1', whatsapp_message_id: null, direction: 'outbound', sender_type: 'ai', message_type: 'text', text: '¡Hola Juan! 👋 Con gusto te ayudo con información sobre Cancún. Para enviarte las mejores opciones, ¿me podrías indicar para cuántas personas viajás y en qué fechas tentativas?', status: 'sent', error_detail: null, created_at: mins(29) },
    { id: 'm3', conversation_id: '1', whatsapp_message_id: 'wamid.3', direction: 'inbound', sender_type: 'customer', message_type: 'text', text: 'Somos 2 personas y queremos viajar del 15 al 20 de julio.', status: 'received', error_detail: null, created_at: mins(25) },
    { id: 'm4', conversation_id: '1', whatsapp_message_id: null, direction: 'outbound', sender_type: 'ai', message_type: 'text', text: 'Perfecto. ¿Tenés algún presupuesto aproximado en mente para el viaje?', status: 'sent', error_detail: null, created_at: mins(24) },
    { id: 'm5', conversation_id: '1', whatsapp_message_id: 'wamid.5', direction: 'inbound', sender_type: 'customer', message_type: 'text', text: 'Entre 25,000 y 30,000 pesos por persona.', status: 'received', error_detail: null, created_at: mins(5) },
  ],
}

export const mockLogs: LogEvent[] = [
  { id: 'l1', type: 'message.inbound', origin: 'whatsapp', conversation_id: '1', detail: 'Mensaje de Juan Pérez: Entre 25,000 y 30,000 pesos por persona.', status: 'success', created_at: mins(5) },
  { id: 'l2', type: 'agent.response', origin: 'agent', conversation_id: '1', detail: 'IA respondió a Juan Pérez.', status: 'success', created_at: mins(4) },
  { id: 'l3', type: 'handoff.started', origin: 'human', conversation_id: '3', detail: 'Admin tomó control de la conversación con Carlos López.', status: 'success', created_at: mins(25) },
  { id: 'l4', type: 'message.outbound', origin: 'human', conversation_id: '3', detail: 'Mensaje manual enviado a Carlos López.', status: 'success', created_at: mins(20) },
  { id: 'l5', type: 'webhook.received', origin: 'whatsapp', conversation_id: '2', detail: 'Webhook de María Gómez (+5491198765432).', status: 'success', created_at: mins(15) },
]

export const mockStats: DashboardStats = {
  activeConversations: 4,
  waitingHuman: 1,
  messagesToday: 18,
  recentErrors: 0,
  whatsappStatus: 'connected',
}
